### BASICS

In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3])  #a= np.array([1,2,3], dtype='int16') 
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [7]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
#get type
a.dtype

dtype('int32')

In [9]:
a.size  #how many items

3

In [10]:
a.itemsize  # each items size

4

In [11]:
#total size
a.nbytes   #a.size * a.itemsize

12

### Accessing and changing specific element, rows, columns etc

In [12]:
x=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
x

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
#get specific element  [row, column]
x[1,5]  #13   x[1,-2]

13

In [15]:
#get a specific row
x[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#get a specicif column
x[:,2]

array([ 3, 10])

In [17]:
#[startindex:endindex:step]
x[0,1:6:2]

array([2, 4, 6])

In [18]:
x[1,5]=20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [19]:
x[:,2]=5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [20]:
x[:,2]=[21,22]
print(x)

[[ 1  2 21  4  5  6  7]
 [ 8  9 22 11 12 20 14]]


In [21]:
# 3-d
y=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#work out side in to get specific element
y[0,1,1]  #4

4

In [25]:
#replace 3-d subset should be of same dimension
y[:,1,:]=[[9,9],[8,8]]
print(y)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing different types of array

In [26]:
#all ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
# all zeros
np.zeros((2,3),dtype='int16')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [29]:
#all same numbers
np.full((2,2), 50)

array([[50, 50],
       [50, 50]])

In [30]:
np.full_like(x,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [31]:
np.full(x.shape, 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [32]:
# random decimal numbers
np.random.rand(4,2)

array([[0.85208781, 0.06470214],
       [0.70223617, 0.22968468],
       [0.53862772, 0.01572739],
       [0.24138691, 0.51622315]])

In [33]:
np.random.random_sample(x.shape)

array([[0.03819224, 0.35451551, 0.3040368 , 0.24015571, 0.03692343,
        0.45432209, 0.45649935],
       [0.29863758, 0.29671363, 0.82772926, 0.9409721 , 0.46423091,
        0.88794925, 0.3791691 ]])

In [35]:
#random integer values
np.random.randint(2,8,size=(2,2))  #2 is inclusive, 8 is exclusive

array([[2, 3],
       [7, 6]])

In [36]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)
r2=np.repeat(arr,3,axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [39]:
output=np.full((5,5),9)
z=np.zeros((3,3))
z[1,1]=1
output[1:-1,1:-1]=z
print(output)

[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]


#### be careful when copying arrays

In [40]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


### mathematics

In [41]:
a=np.array([1,2,3])

In [43]:
a+=2
a

array([5, 6, 7])

In [46]:
a -= 2
a

array([3, 4, 5])

In [47]:
a *=2

In [49]:
a / 2

array([3., 4., 5.])

In [50]:
np.sin(a)

array([-0.2794155 ,  0.98935825, -0.54402111])

In [51]:
a ** 2

array([ 36,  64, 100], dtype=int32)

### Linear algebra

In [52]:
a=np.ones((2,3))
b=np.full((3,2),4)
np.matmul(a,b)

array([[12., 12.],
       [12., 12.]])

In [53]:
#find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [54]:
stats=np.array([[1,2,3],[4,5,6]])

In [56]:
np.min(stats)

1

In [57]:
np.max(stats)

6

In [59]:
np.min(stats,axis=1)

array([1, 4])

In [60]:
np.sum(stats)

21

In [62]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing array

In [63]:
before=np.array([[1,2,3,4],[5,6,7,8]])
before.shape

(2, 4)

In [65]:
after=before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
#vertical stacking
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
v3=np.vstack([v1,v2])
v3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Miscelleneous

In [5]:
#load data from txt file
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 23],
       [ 3,  5,  4,  6,  8,  2,  3,  8,  9, 10, 12],
       [16, 25, 21, 34, 23, 32,  2,  4,  8, 98, 65]])

In [6]:
#advanced indexing and boolean masking
filedata > 12

array([[False, False, False, False, False, False, False, False, False,
        False,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [ True,  True,  True,  True,  True,  True, False, False, False,
         True,  True]])

In [7]:
filedata[filedata>12]

array([23, 16, 25, 21, 34, 23, 32, 98, 65])

In [9]:
np.any(filedata>12, axis=0)  #np.all

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True,  True])

In [10]:
((filedata>12) & (filedata<15))

array([[False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False]])

In [8]:
#you an index with a list in Numpy
z=np.array([1,2,3,4,5,6,7,8,9,10])
z[[0,2,5]]

array([1, 3, 6])

### Practice

In [11]:
d=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
d[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [13]:
d[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [14]:
d[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])